apiVersion: apm.k8s.elastic.co/v1alpha1
kind: ApmServer
metadata:
  name: apm-server-server
  namespace: default
spec:
  version: 7.3.0
  nodeCount: 1
  elasticsearchRef:
    name: elasticsearch-sample
  http:
    service:
      spec:
        type: LoadBalancer

