apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: "7.3.0"
  nodeCount: 1
  elasticsearchRef:
    name: "elasticsearch-sample"
  http:
    service:
      spec:
        type: LoadBalancer
#    tls:
#      selfSignedCertificate:
#        subjectAltNames:
#        - dns: kibana-sample-kb-http.default.svc

